# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-11-20 23:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dog_name', models.CharField(max_length=25)),
                ('breed', models.CharField(max_length=25)),
                ('bio', models.CharField(max_length=225)),
                ('dog_pic', models.ImageField(blank=True, default='default.png', upload_to='')),
            ],
        ),
    ]
