# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-11-21 00:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0002_dog'),
    ]

    operations = [
        migrations.AddField(
            model_name='dog',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='dog',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
