# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-11-21 00:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0003_auto_20191121_0012'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dog',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='dog',
            name='breed',
        ),
        migrations.RemoveField(
            model_name='dog',
            name='dog_name',
        ),
    ]
