# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-11-21 00:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0004_auto_20191121_0028'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dog',
            old_name='dog_pic',
            new_name='image',
        ),
    ]
