# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-11-21 00:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0005_auto_20191121_0033'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Dog',
        ),
    ]
