# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-11-21 00:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0007_dog'),
    ]

    operations = [
        migrations.AddField(
            model_name='dog',
            name='bio',
            field=models.CharField(default=True, max_length=225),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dog',
            name='breed',
            field=models.CharField(default=True, max_length=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dog',
            name='dog_name',
            field=models.CharField(default=True, max_length=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dog',
            name='dog_size',
            field=models.CharField(default=True, max_length=25),
            preserve_default=False,
        ),
    ]
