# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-11-21 22:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0011_auto_20191121_1833'),
    ]

    operations = [
        migrations.AddField(
            model_name='dog',
            name='like',
            field=models.ManyToManyField(related_name='likes', to='first_app.User'),
        ),
    ]
