# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-11-21 22:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0012_dog_like'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dog',
            name='like',
        ),
    ]
