# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-11-21 23:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0014_dog_like'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dog',
            name='like',
        ),
        migrations.AddField(
            model_name='dog',
            name='dog_liked',
            field=models.ManyToManyField(related_name='_dog_dog_liked_+', to='first_app.Dog'),
        ),
    ]
