# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-11-22 01:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0017_remove_dog_dog_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='dog',
            name='password',
            field=models.CharField(default=True, max_length=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dog',
            name='username',
            field=models.CharField(default=True, max_length=15),
            preserve_default=False,
        ),
    ]
