# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-11-22 17:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0022_auto_20191122_1739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dog',
            name='dog_owner',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, related_name='my_dogs', to='first_app.User'),
            preserve_default=False,
        ),
    ]
