# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-11-22 19:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0023_auto_20191122_1745'),
    ]

    operations = [
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='dog',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='dog',
            name='dog_liked',
        ),
        migrations.RemoveField(
            model_name='dog',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='user',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='user',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='like',
            name='dog_liked',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='first_app.Dog'),
        ),
        migrations.AddField(
            model_name='like',
            name='liker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='the_likes', to='first_app.Dog'),
        ),
    ]
