# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-11-21 22:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0013_remove_dog_like'),
        ('second_app', '0002_auto_20191121_2249'),
    ]

    operations = [
        migrations.CreateModel(
            name='Connection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('like', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='first_app.Dog')),
            ],
        ),
        migrations.RemoveField(
            model_name='like',
            name='like',
        ),
        migrations.DeleteModel(
            name='Like',
        ),
    ]
