# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-11-21 23:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0013_remove_dog_like'),
        ('second_app', '0003_auto_20191121_2259'),
    ]

    operations = [
        migrations.AddField(
            model_name='connection',
            name='dislike',
            field=models.ManyToManyField(related_name='dislikes', to='first_app.Dog'),
        ),
        migrations.RemoveField(
            model_name='connection',
            name='like',
        ),
        migrations.AddField(
            model_name='connection',
            name='like',
            field=models.ManyToManyField(related_name='likes', to='first_app.Dog'),
        ),
    ]
