# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-11-22 17:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('second_app', '0004_auto_20191121_2311'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='connection',
            name='dislike',
        ),
        migrations.RemoveField(
            model_name='connection',
            name='like',
        ),
        migrations.DeleteModel(
            name='Connection',
        ),
    ]
